# Project information
site_name: Conio SDK Documentation
site_url: https://sdk-docs.conio.com/

# Repository
repo_name: conioteam.github.io
repo_url: https://github.com/Conio/conio.github.io

# Navigation
nav:
    - home: index.md
    - home: index.en.md
    - Changelog: 'CHANGELOG.en.md'
    - installation:
      - iOS: 'installation/iOS.md'
      - iOS: 'installation/iOS.en.md'
      - Android: 'installation/Android.md'
      - Android: 'installation/Android.en.md'
    - configuration: 'configuration/Configuration.md'
    - configuration: 'configuration/Configuration.en.md'
    - operations:
      - general: 'operation/Operation.md'
      # - general: 'operation/Operation.en.md'
      - cryptoRequest: 'operation/CryptoRequest.md'
      # - cryptoRequest: 'operation/CryptoRequest.en.md'
    - user: 'user/User.md'
    - user: 'user/User.en.md'
    - exchangeOperations: 'exchange/Exchange.md'
    - exchangeOperations: 'exchange/Exchange.en.md'

# Plugins
plugins:
  - search
  - i18n:
      languages:
        it: "Italiano"
        en: "English"
      default_language: 'it'
      no_translation:
        en: "This page isn't translated to English."
        it: "Questa pagina non è tradotta in italiano"
      translate_nav:
        en:
          home: "Home"
          installation: "Installation"
          configuration: "Configuration"
          operations: "Operations"
          general: "Overview"
          cryptoRequest: "Crypto Requests"
          user: "User"
          exchangeOperations: "Exchange operations"
        it:
          home: "Home"
          installation: "Installazione"
          configuration: "Configurazione"
          operations: "Operazioni"
          general: "Generale"
          cryptoRequest: "Crypto Request"
          user: "Utente"
          exchangeOperations: "Operazioni sul mercato"


# Copyright
# TBD

# Theme
theme:
  name: material
  locale: it
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    # - navigation.tabs
    - navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: blue
    accent: blue

extra:
  alternate:
    # Switch to English
    - name: English
      link: index.en/
      lang: en

    # Switch to Italian
    - name: Italiano
      link: ""
      lang: it
