# Project information
site_name: Conio SDK Documentation
site_url: https://sdk-docs.conio.com/

# Repository
repo_name: conioteam.github.io
repo_url: https://github.com/Conio/conio.github.io

# Navigation
nav:
    - Home: index.md
    - Changelog: 'CHANGELOG.md'
    - 'Installazione':
      - 'iOS': 'installation/iOS.md'
      - 'Android': 'installation/Android.md'
    - 'Configurazione': 'configuration/Configuration.md'
    - 'Operazioni':
      - 'Generale': 'operation/Operation.md'
      - 'Crypto Request': 'operation/CryptoRequest.md'
    - 'Utente': 'user/User.md'
    - 'Operazioni sul mercato': 'exchange/Exchange.md'

# Copyright
# TBD

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    # - navigation.tabs
    - navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: blue
    accent: blue

# extra:
#   alternate:
#
#     # Switch to English
#     - name: English
#       link: https://sdk-docs.conio.com/en/
#       lang: en
#
#     # Switch to German
#     - name: Italiano
#       link: https://sdk-docs.conio.com/
#       lang: it
