# Project information
site_name: Conio SDK Documentation
site_url: https://sdk-docs.conio.com/

# Repository
repo_name: conioteam.github.io
repo_url: https://github.com/Conio/conio.github.io

# Navigation
nav:
  - Home: index.md
  - Changelog: CHANGELOG.md
  - Installation:
    - iOS: Installation/Ios.md
    - Android: Installation/Android.md
  - Configuration:
    - iOS: Configuration/Ios.md
    - Android: Configuration/Android.md
  - User Service: Features/UserService.md
  - Trading Info Service: Features/TradingInfoService.md
  - Wallet Service: Features/WalletService.md
  - BTC Transaction Management Service: Features/BtcTransactionManagementService.md
  - Trading Buy Service: Features/TradingBuyService.md
  - Trading Sell Service: Features/TradingSellService.md
  - Trading Price Service: Features/TradingPriceService.md
  - Swap Service: Features/SwapService.md
  - Transfer Service: Features/TransferService.md
  - Activities Service: Features/ActivitiesService.md
    
# Plugins
plugins:
  - search
  - pdf-export:
      enabled: !ENV [PDF_EXPORT, true]
      verbose: true
      combined: true
      combined_output_path: pdf/ConioSDK_Docs.pdf

# Theme
theme:
  name: material
  locale: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/images/logo.webp
  features:
    - navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: blue greys
    accent: teal
