# Project information
site_name: Conio SDK Documentation
site_url: https://sdk-docs.conio.com/

# Repository
repo_name: conioteam.github.io
repo_url: https://github.com/Conio/conio.github.io

# Navigation
nav:
  - Home: index.md
  - Changelog: CHANGELOG.md
  - Installation:
    - iOS: Installation/iOS.md
    - Android: Installation/Android.md
  - Configuration:
    - iOS: Configuration/iOS.md
    - Android: Configuration/Android.md
  - Services:
    - Categories: Features/index.md
    - Common errors: Features/Errors.md
    - User Service:
      - Features/UserService/Login.md
      - Features/UserService/Signup.md
      - Features/UserService/Logout.md
      - Features/UserService/FetchLegalAcceptances.md
      - Features/UserService/FetchPermissions.md
      - Features/UserService/AcceptNewLegalAcceptances.md
    - Wallet Service:
      - Features/WalletService/FetchBalances.md
      - Features/WalletService/FetchMnemonic.md
    - Activities Service:
      - Features/ActivitiesService/FetchActivities.md
      - Features/ActivitiesService/FetchActivity.md
    - Trading Price Service:
      - Features/TradingPriceService/FetchPrice.md
      - Features/TradingPriceService/FetchHistoricalPrice.md
      - Features/TradingPriceService/FetchAllPrices.md
      - Features/TradingPriceService/FetchTradableCryptocurrenciesMetadata.md
    - Trading Info Service:
      - Features/TradingInfoService/FetchTradingFees.md
      - Features/TradingInfoService/FetchTradingSummary.md
      - Features/TradingInfoService/FetchTradingLimits.md
      - Features/TradingInfoService/FetchTradingReport.md
    - BTC Transaction Service:
      - Features/BtcTransactionManagementService/FetchAddress.md
      - Features/BtcTransactionManagementService/SendBitcoin.md
      - Features/BtcTransactionManagementService/SpeedUpTransaction.md
      - Features/BtcTransactionManagementService/FetchTransactionAvailableFees.md
      - Features/BtcTransactionManagementService/FetchSpeedUpAvailableFees.md
    - Buy Service:
      - Features/TradingBuyService/CreateBid.md
      - Features/TradingBuyService/UpdateBid.md
      - Features/TradingBuyService/FetchBid.md
      - Features/TradingBuyService/Buy.md
    - Sell Service:
      - Features/TradingSellService/CreateAsk.md
      - Features/TradingSellService/UpdateAsk.md
      - Features/TradingSellService/FetchAsk.md
      - Features/TradingSellService/Sell.md
    - Swap Service:
      - Features/SwapService/CreateSwap.md
      - Features/SwapService/UpdateSwap.md
      - Features/SwapService/FetchSwap.md
      - Features/SwapService/Swap.md
    - Transfer Service:
      - Features/TransferService/CreateTransfer.md
      - Features/TransferService/UpdateTransfer.md
      - Features/TransferService/FetchTransfer.md
      - Features/TransferService/Transfer.md
    
# Plugins
plugins:
  - search
  - pdf-export:
      enabled: !ENV [PDF_EXPORT, true]
      verbose: true
      combined: true
      combined_output_path: pdf/ConioSDK_Docs.pdf

# Theme
theme:
  name: material
  locale: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: assets/images/logo.webp
  features:
    - navigation.instant
    # - navigation.expand
  palette:
    scheme: default
    primary: blue greys
    accent: teal
